package main

import (
	"encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	APIVersion              = "templates.stolos.cloud/v1"
	KindContainerDeployment = "ContainerDeployment"
)

// ContainerDeployment is the type representing our CustomResource.
// It contains Type and Object meta as found in typical kubernetes objects and a spec.
// Do not provide a Status Object as that is automatically generated by the ATC.
type ContainerDeployment struct {
	metav1.TypeMeta
	metav1.ObjectMeta `json:"metadata"`
	Spec              ContainerDeploymentSpec `json:"spec"`
}

// ContainerDeploymentSpec defines the desired container workload.
type ContainerDeploymentSpec struct {
	Image    string `json:"image"`
	Replicas int32  `json:"replicas,omitempty" Default:"1"`
	Port     int32  `json:"port,omitempty" Default:"80"`
}

// MarshalJSON sets apiVersion and kind so users do not need to explicitly fill them out.
func (c ContainerDeployment) MarshalJSON() ([]byte, error) {
	c.Kind = KindContainerDeployment
	c.APIVersion = APIVersion

	type ContainerDeploymentAlt ContainerDeployment
	return json.Marshal(ContainerDeploymentAlt(c))
}

// UnmarshalJSON validates apiVersion and kind on input resources.
func (c *ContainerDeployment) UnmarshalJSON(data []byte) error {
	type ContainerDeploymentAlt ContainerDeployment
	if err := json.Unmarshal(data, (*ContainerDeploymentAlt)(c)); err != nil {
		return err
	}
	if c.APIVersion != APIVersion {
		return fmt.Errorf("unexpected api version: expected %s but got %s", APIVersion, c.APIVersion)
	}
	if c.Kind != KindContainerDeployment {
		return fmt.Errorf("unexpected kind: expected %s but got %s", KindContainerDeployment, c.Kind)
	}
	return nil
}
