package main

import (
	"encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	APIVersion = "templates.stolos.cloud/v1"
	KindBase   = "Base"
)

// Base is the type representing our CustomResource.
// It contains Type and Object meta as found in typical kubernetes objects and a spec.
// Do not provide a Status Object as that is automatically generated by the ATC.
type Base struct {
	metav1.TypeMeta
	metav1.ObjectMeta `json:"metadata"`
	Spec              BaseSpec `json:"spec"`
}

// Our Base Specification
type BaseSpec struct {
	SomeProperty string `json:"SomeProperty"`
}

// Custom Marshalling Logic so that users do not need to explicity fill out the Kind and ApiVersion.
func (base Base) MarshalJSON() ([]byte, error) {
	base.Kind = KindBase
	base.APIVersion = APIVersion

	type BaseAlt Base
	return json.Marshal(BaseAlt(base))
}

// Custom Unmarshalling to raise an error if the ApiVersion or Kind does not match.
func (base *Base) UnmarshalJSON(data []byte) error {
	type BaseAlt Base
	if err := json.Unmarshal(data, (*BaseAlt)(base)); err != nil {
		return err
	}
	if base.APIVersion != APIVersion {
		return fmt.Errorf("unexpected api version: expected %s but got %s", APIVersion, base.APIVersion)
	}
	if base.Kind != KindBase {
		return fmt.Errorf("unexpected kind: expected %s but got %s", KindBase, base.Kind)
	}
	return nil
}
